#!/bin/zsh

FIRST_ANGLE=$1
SECOND_ANGLE=$2
THIRD_ANGLE=$3

IS_ANGLE_EQUAL=1

if [ $FIRST_ANGLE -eq $SECOND_ANGLE -a $FIRST_ANGLE -ne $THIRD_ANGLE ]; then
    IS_ANGLE_EQUAL=0
fi


if [ $SECOND_ANGLE -eq $THIRD_ANGLE -a $SECOND_ANGLE -ne $FIRST_ANGLE ]; then
    IS_ANGLE_EQUAL=0
fi


if [ $FIRST_ANGLE -eq $THIRD_ANGLE -a $FIRST_ANGLE -ne $SECOND_ANGLE ]; then
    IS_ANGLE_EQUAL=0
fi

echo $IS_ANGLE_EQUAL
